# Generated by Django 3.1 on 2020-09-23 16:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_out',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
