# Generated by Django 3.1 on 2020-09-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200923_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.check_out'),
        ),
    ]
