# Generated by Django 3.1 on 2020-09-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.check_out'),
        ),
    ]
